# Generated by Django 5.1.6 on 2025-02-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventparticipant',
            old_name='visitor',
            new_name='member',
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('organizer', 'Organizer')], max_length=50),
        ),
    ]
